name: money
description: Class for math with money (with decimals places).
version: 0.9.1
homepage: https://github.com/fregate/money
issue_tracker: https://github.com/fregate/money/issues
repository: https://github.com/fregate/money

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
